### ISSUE TITLE
Listen events separately from the instance data

### ISSUE THREAD

**Issue by monolithed** [vuejs/Discussion#117]
I've a custom directive like this abstract code:

```html
<!-- foo.html -->
<div v-on="click: reload" v-foo='' class="foo" />
```

```js
// options.js
export default {
	el: () => '.foo',
        methods: {
             reload () {
                 // I can not pass any logic in this file and the method as well  
                 // (my architectural restrictions)
            }
        }
}
```

```js
// directive.js
import Vue from 'vue';
import options from './options;

Vue.directive('foo', {/* ... */})
export default Vue.extend(options);
```

```js
// events.js
import Directive from './directive;

var foo = new Directive;
```

I would like to listen events separately from the instance data like:

```js
foo.$on('click', () => {});
```

Is it possible?

**Comment by TMiguelT** [comment]
Your code isn't particularly clear because when you `import Directive from './directive`, Directive is actually a component constructor, not a directive. 

But to answer your question, yes you can absolutely add an event listener separately from the instance data. Here's an example ([JSFiddle](http://jsfiddle.net/gzud1279/1/)):
```javascript
//Define a new component
var myComponent = Vue.extend({
    el: function () {
        return document.createElement('p')
    },
    template: "foo",
    ready: function(){
        this.$emit("ready");
    }
});

//Create an instance of that component
var instance = new myComponent();

//Listen for the 'ready' event on that instance. This is a custom event, not the same as the ready callback.  
instance.$on("ready", function(){
    alert("Ready!");
});

//Add this component to the DOM
instance.$appendTo('body');
```

However I've never seen a situation where manually calling a component constructor function is a good idea. Surely you can use a `v-component` and then call `$dispatch()` on the child component to alert the parent instead of manually adding an event listener.

**Comment by monolithed** [comment]
I got it, more thanks for your detailed response!
