### ISSUE TITLE
Making custom input components (that act like <input> elements)

### ISSUE THREAD

**Issue by TMiguelT** [vuejs/Discussion#120]
I'm working on a Vue component that contains an `<input>` element which will have an associated `v-model` directive. However I'm intending to make this component reuseable, so that it can be used to edit data on the parent viewmodel. 

Ideally I could do it something like this: [Fiddle](http://jsfiddle.net/fdzwv01y/), where I use a `v-with` to pass in the variable to modify. However, since `v-with` only copies data to the child component, modifying it in the child component won't affect it in the parent. 
```html
<!--Parent template-->
<my-input v-with="bound: varA"></my-input>

<!--Child template-->
<input type="text" v-model="bound">
```

The other option is to use `inherit: true`, and pass in the keypath to modify, but that requires `v-model` to work dynamically, which it doesn't. Instead you get the error `"[Vue warn]: Invalid expression. Generated function body:  {{scope.keypath}}"`: [Fiddle](http://jsfiddle.net/qffqwd9z/1/)
```html
<!--Parent template-->
<my-input v-with="keypath: 'varA'"></my-input>

<!--Child template-->
<input type="text" v-model="{{keypath}}">
```

How then can I make custom input components?

**Comment by RangerMauve** [comment]
Maybe it'd be possible if your elements emitted an `input` or `change` DOM event or something similar so that v-model listener further up would caputre it and interpret it as it's current element being an input. I'm not sure if v-model accepts being assigned to non `input` elements, though.

**Comment by yyx990803** [comment]
Seems no longer an issue with two-way `v-with` in 0.11.5 :)

**Comment by the48ers** [comment]
This issue seems to have re-appeared now that 'v-with' is deprecated.

Using Vue.js v0.12.7. I cannot figure out how to dynamically set the input's v-model (using either data or props). 

I have lots of inputs on the main template page, this example shows three and would provide an elegant solution:


<div class="view" v-transition>
  <app-input prop-id="lastName" label1="Last Name"</app-input>
  <app-input prop-id="firstName" label1="First Name"</app-input>
  <app-input prop-id="email" label1="E-mail"</app-input>
</div>

// Filename: setup/index.js
module.exports = {
  template: require('./template.html'),
  components: {
    'app-input': require('../../components/input')
  }
}

// Filename: components/input/index.js
module.exports = {
  el: function () {
	return '#demo'
  },
  data: function () {
    return {
      lastName: 'Smith'
    }
  },
  template: require('./template.html'),
  props: ['prop-id','label1']
}



<div id="demo" class="form-group">
	<div class="input-group">
		<label for="{{propId}}" class="control-label labelicon">{{label1}}</label>
		<input class="form-control" type="text" v-model="{{propId}}" id="{{propId}}" name="{{propId}}">
	</div>
</div>

I will be filling in values for all inputs using v-model and AJAX from a Laravel API back-end. Build with Webpack (btw, awesome github repo on that and lazy loading! SOLD!). 

Issue:
Within "components/input/template.html" using v-model="{{propId}}", in Chrome DevTools I get "[Vue warn]: Invalid expression. Generated function body:  {{scope.propId}}".
{{propId}} should evaluate to lastName (from the 'prop-id' prop of component 'app-input') and lastName is 'Smith' from 'components/input/index.js', and so the input would be expected to equal 'Smith' as if v-model="lastName", but it generates the error.

With 'v-with' deprecated as you mentioned in the reason for closing this issue as it was working with 'v-with', might there be another method? Seems a super elegant method is thwarted by the error. 

Big picture, I am super impressed with the evolution of vuejs, I can work around this without templating, but this superior functionality seems so close. :)

**Comment by ArthurGuy** [comment]
I have just run into the same problem, a solution or workaround would be great

**Comment by GuillaumeLeclerc** [comment]
I also think it should be reopened. It is very important to be able to abstract more complex data input

**Comment by ryanwinchester** [comment]
+1

**Comment by GuillaumeLeclerc** [comment]
I found out how to do this:

In your component: 

```
...
props: {
  msg: {
    required: true,
    twoWay: true
  }
},
...
```

And in the parent: 

```
<template>
<child :msg.sync="msg"></chil>
</template>
...
data : function() {
  return {
    msg: 'hi',
  }
}
```

**Comment by weiying-chen** [comment]
@GuillaumeLeclerc +1 Thanks a lot! I spent the whole morning trying to figure out this.
