### ISSUE TITLE
Lots of garbage in dbmon benchmark

### ISSUE THREAD

**Issue by nkovacs** [vuejs/Discussion#194]
The js heap rapidly rises from about 40 Mb to about 140 Mb, then the garbage collector collects about 100Mb, and the whole process starts again. According to chrome's profiler, there are smaller GC cycles (~7Mb) in between the big 100Mb ones.
With mithril, it mostly stays in the 30-40Mb range.
Any ideas what's causing this?

**Comment by yyx990803** [comment]
This is likely because Vue's observation mechanism creates corresponding observers, deps and watchers when a dataset is observed. The benchmark is rapidly replacing the entire dataset, thus causing all those objects created for the previous dataset to be GCed.

Note that it if you run the Mithril example for long enough, it's heap, despite very constant drops, is steadily going up in the long term. I recorded its heap timeline until Chrome ran out of buffer, and its memory usage grown up to 500MB before a huge GC put it back.

So, it seems it's more about the implementation difference causing different GC behavior. For Vue, it's fast 40~140MB cycles; for Mithril, it's a slow but 40~500MB cycle. IMO I'd rather go with the one with a smaller maximum, given similar visible rendering speed.

Finally, the dbmon benchmark is more like a stress-testing benchmark - if a framework can handle dbmon, then it is very unlikely you'll get into rendering/memory issues in a real application.

**Comment by nkovacs** [comment]
Thanks for the detailed response.
You're right, I did not notice the steady increase in Mithril, though in my case it only goes up to about 75Mb before a GC drop down to 15Mb (50% mutation rate in both cases).
