### ISSUE TITLE
Google maps and vue not really working fine

### ISSUE THREAD

**Issue by Roadirsh** [vuejs/Discussion#275]
Hello,
I found a bug, maybe it's my fault, don't really know but here it is:
I use Vue.js to manage my app who use the google maps API, i have set the 
variable map in the vue data attribute like this:
this.map = new google.maps.Map(document.getElementById('map-canvas'),
                mapOptions);
So i could have access to it in every method of my vue object. Now here the trick it's working fine in a screen > 600px BUT i get Cannot redefine property: "chrome" in chrome, Cannot redefine property: "top" in firefox, Cannot redefine property: lpcustomEvent with LastPass on when i load the page with a width < 600px. 
http://puu.sh/iZSq0/daac1404db.png

I fix the bug by making the map variable global outside the Vue object. So i don't really know if it's from Google, Vue or me.
Sorry for my english :)

**Comment by young-steveo** [comment]
@Roadirsh Data in VueJS needs to be raw data (i.e. `JSON.parse`-able).  The `google.maps.Map` object does not fit that requirement.

**Comment by adam12** [comment]
I noticed this yesterday when upgrading to 0.12.7; moving the map variable outside of the Vue $data scope was the solution.

**Comment by yyx990803** [comment]
Yeah, rule of thumb: don't try to observe complex objects with behavior. You can still attach it to your Vue instance, just don't make it a reactive property in your `data` option.

**Comment by Roadirsh** [comment]
Ah i didn't know that! 
Thanks for the explanation ahah

**Comment by praveenpuglia** [comment]
> You can still attach it to your Vue instance, just don't make it a reactive property in your data option.

@yyx990803 - can you please elaborate a little. newbie in VueJS and faced this issue today.

**Comment by yyx990803** [comment]
A property becomes reactive if it is returned as part of the initial data:

``` js
data: function () {
  return {
    thisIsReactive: 123
  }
}
```

But if you only attach it in the `created` hook (which is called after the data initialization), it will be a normal, non-reactive property:

``` js
created: function () {
  this.nonReactive = 123
}
```

**Comment by simplesmiler** [comment]
@yyx990803 is this behavior documented and can be relied on?
Wouldn't it better to introduce a new section `plain` (name is a subject to change) alongside `data`?

There's also note in the documentation, that properties that start with `_` or `$` are not reactive. Or am I missing something?

**Comment by yyx990803** [comment]
@simplesmiler the rule is pretty simple and reliable: if a property appears in `data` or as a `prop`, it's reactive; otherwise it's not. The prefix rule also applies, of course.

**Comment by gocanto** [comment]
Hello @yyx990803.

I got this situation where I am using the google map API to complete an address form, as so: https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform

So the problem here is those inputs are updated through an external javascript code, outside my vue object. 

Now, even when I have these inputs linked to my vue object using v-model, they don't update its data .

This is the example: 

## Google import 

```
<script src="https://maps.googleapis.com/maps/api/js?key={{ env('GOOGLE_MAP_KEY') }}&libraries=places&callback=googleInitAutocomplete" async defer></script>
```

## Google script

```
function googleInitAutocomplete() {

    autocomplete = new google.maps.places.Autocomplete(
        (document.getElementById('autocomplete')),
        {
            types: ['geocode']
        }
    );

    autocomplete.addListener('place_changed', googleFillInAddress);
}

function googleFillInAddress()
{
    var place = autocomplete.getPlace();

    var address = {
        route: 'long_name',
        country: 'long_name',
        administrative_area_level_1: 'long_name',
        locality: 'long_name',
        postal_code: 'short_name'
      };

    for (var i = 0; i < place.address_components.length; i++) {

        var addressType = place.address_components[i].types[0];

        if (address[addressType]) {

            console.log(addressType + ' >>> ' + place.address_components[i][address[addressType]] + ' | ' + document.getElementById(addressType).value);
            var val = place.address_components[i][address[addressType]];
            document.getElementById(addressType).value = val;
        }
    }
}
```

## My vue object

```
new Vue({
        el: '#npl-mentorsApproval',
        data:
        {
            trans: '',
            address: {},
            route: '',
            map: '',
            googleMapScript: ''
        }
}
```

## My HTML

```
<input type="text" v-model="route" placeholder="Address" class="form-control input-lg">
```

How can I update this data from my google script? 

thanks

**Comment by ShahanurSharif** [comment]
@gocanto nobody cares

**Comment by SMen1** [comment]
Hello gocanto
I am sure that you have long solved this issue, but for anyone else struggling at first to put Google javascript in as methods/computed and updating data, try setting your vue up not as:

new Vue({ etc.
but 
var app = new Vue({ etc. (where 'app' is your chosen variable name)

You can then target your data by referencing 'app' instead of 'this'.

so this.yourData.yourNestedData = googleMapsResponseData becomes
app.yourData.yourNestedData = googleMapsResponseData

from within your Google Maps javascript.
and you can then update your data.

https://vuejsdevelopers.com/2017/03/05/vue-js-reactivity/ was where I was reminded of this.
