### ISSUE TITLE
When to use filters?

### ISSUE THREAD

**Issue by swift1** [vuejs/Discussion#294]
This might be a stupid question, but I'll ask anyway.

Given the following:
````javascript
data: {
	columns: [{colName: "col1", "width": 50},{"colName": "col2", "width": 50}]
}
````

There's at least two ways to get the colName property.

A) The easy way:
````html
<span class="box" v-repeat="column: columns">
	{{ column.colName }}
</span>
````

B) The hard way:
````javascript````
filters: {
	getColName: function(col){
		return col.colName;
	}
}
````
````html
<span class="box" v-repeat="column: columns">
	{{ column | getColName }}
</span>
````

What's best practice? Or does it even matter? (I assume the filters are just for when you wanna do something a bit more advanced, but I'd just like to get it confirmed.)

**Comment by Nirazul** [comment]
Generally: 
If you want to have easily accessible operations that shall work the same way all over your application, then you can use a filter.
If it's a piece of code, that is unlikely to ever occur again (like in your example), then it's easier to use a method or computed attribute.

**Comment by yyx990803** [comment]
The example you gave is probably not the best one, since accessing a property is simple enough to just use directly.

But take some of the built-in filters as examples: if you want to capitalize a string directly within the expression, you'd have to write:

``` html
{{ str.charAt(0).toUpperCase() + str.slice(1) }}
```

It is clunky, doesn't directly express what you are trying to do, and it would be terrible to have to do this every time you want to capitalize something in your app. A filter makes it much cleaner:

``` html
{{ str | capitalize }}
```

**Comment by swift1** [comment]
True, thanks for your replies.
