### ISSUE TITLE
Data driven components vs dynamically spawned components

### ISSUE THREAD

**Issue by groovy9** [vuejs/Discussion#488]
I initially commented on an old, closed ticket about dynamically spawning components with the $compile internal function, but thought I'd post my use case here to try to wrap my head around how to do it in a data-driven style.

This is a single-page app centered around a tab set.  Imagine you start with one tab holding a data grid component showing a database table of something like employees, vendors, jobs, etc.  You spend most of your time focused on one particular table, but occasionally need access to as many as ten.

From there, you might open a new tab with a new data set, or may edit a record in a data set.  The edit component can't obscure the data grid as you may have to go back and forth and can be fairly complex, so it also goes in a new tab.  

You may need to edit multiple related records at once, or may get interrupted while editing thing A and have to go edit thing B, returning to A later, etc.

Each edit form is a separate component, e.g. fooEdit, barEdit, bazEdit, referring to database tables foo, bar and baz.  I may not touch foo at all this week, and then may use it every day next week.

For this use case, I'm struggling to see how to go about pre-defining all of these components in a way that would gracefully allow me to have open an arbitrary combination of grids and edits.

For proof of concept, I got it working by dynamically appending tab and tab content markup with $('#foo').append() and then hitting it with this.$compile, which I'm aware is not recommended am afraid it'll change/break in future releases. 

 I'd love to avoid that, but I'm not seeing a way to do it.  Ideas, anyone?

**Comment by simplesmiler** [comment]
What you need to do in this situation is to decompose, because you have multiple dimensions of types.
First dimension is "tab types" (table editor, record editor, etc.). Second dimension is "models types" (employees, vendors, jobs, etc.).

With that in mind I would start with the following (using just Vue):
1. Track the tabs with `vm.tabs` list (e.g. `{ type: 'table-editor', model: 'vendors', state: {} }`);
2. Track the active tab with `vm.tab` field;
3. Use a `<component :is="tab.type" :model="tab.model" :state.sync="tab.state">` to display active tab;
4. Inside of the tab components use partials or sub-components to display the sections that are polymorphic based on the `model` prop.

---

EDIT: also, just so you know, this issue tracker is deprecated in favor of the [forum](http://forum.vuejs.org/) and [chat](https://gitter.im/vuejs/vue).
