### ISSUE TITLE
Intro / tutorial for line "next"?

### ISSUE THREAD

**Issue by imrefazekas** [vuejs/Discussion#496]
Dear All,

I'm about to enter Vue.js and would start with line 2.0 from the beginning.
Is a proper tutorial is planned for this new version? I would not spend time on learning 1.0 if 2.0 will be available the time I finish learning 1.0.

Thanks!

**Comment by simplesmiler** [comment]
Hello!

First things first, `vue/Discussion` is deprecated, and we encourage you to discuss things on [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue).

As for the question, 2.0 is not settled yet. You can check out current draft of [2.0 features](https://github.com/vuejs/vue/wiki/2.0-features) and see that it won't be much different from 1.x.

Also along with 2.0 we will release 2.0-migration, that will be fully compatible with existing 1.x code and also 2.0 code, and will point you to the cases in your code that will stop working under 2.0, so that you can migrate case by case. We already did this when moving 0.x -> 1.0, and it proved to be very successful.

You can safely start learning 1.x now, double checking against the list of 2.0 features.

**Comment by imrefazekas** [comment]
Thanks, sorry for the post. Switched to gitter!
