### ISSUE TITLE
VueJS doesn't update when browser tab not focused?

### ISSUE THREAD

**Issue by Pistos** [vuejs/Discussion#76]
In my app, I have added a `vm.$watch('some_field', ...)` which updates `document.title` using `some_field`'s value.  This works fine, but only when the browser tab is focused.  When the tab is not focused, the change only occurs when I switch to the tab to make it the active browser tab.

Is there any way to fix or work around this?  A "force redraw" of sorts?  Or a "don't require tab focus" setting?

**Comment by rayfranco** [comment]
I'm having the same issue when trying to `vm.$set('volume',0)` on `visibilitychange` event and it is not possible since the watchers are executed on `nextTick` (I guess).
Maybe we could have an util method that allow us to force all `nextTick`'s to be executed. This way I could solve my problem and @Pistos could set his own setTimeout too.

**Comment by TMiguelT** [comment]
I have this problem as well, and it means that every time you try to open a link in a new tab, that tab remains almost blank until you focus it, which defeats the purpose of opening lots of tabs.

As everyone pointed out, this is because Vue.nextTick uses requestAnimationFrame. When you change it to only use setTimeout, all the problems fix themselves. My question is why are we using requestAnimationFrame at all? Isn't it intended for games that need to render sprites each frame? What's wrong with setTimeout?

**Comment by TMiguelT** [comment]
And it looks like [Chrome](http://src.chromium.org/viewvc/chrome?revision=75973&view=revision) and [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=633421#c10) do limit inactive tabs to running setInterval at most once per second, which isn't great, but it's better than never.

**Comment by yyx990803** [comment]
next patch will remove the usage of rAF (instead using setTimeout / MutationObserver when possible)

**Comment by Pistos** [comment]
Yeehaw!

**Comment by thelinuxlich** [comment]
very good!

**Comment by joeweiss** [comment]
Terrific!
